version: 2
updates:
  # NuGet dependency updates
  - package-ecosystem: "nuget"
    directory: "/" # Location of package files (root)
    schedule:
      interval: "weekly"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflow files
    schedule:
      interval: "weekly"
